### ISSUE TITLE
Error with facebook rtmp

### ISSUE THREAD

**Issue by skrosoft** [qwantix/php-rtmp-client#5]
Hi @qwantix 

I have a error 500 using your library with facebook live.

Warning: unpack(): Type N: not enough input, need 4, have 1
500 Internal Server Error - ContextErrorException

Error line 109:

$m = unpack("N","\x00".substr($this->_data,$this->_index,3)); 

I'm looking for a way to stop streaming using rtmp protocol.

This is my code:

`require 'RtmpClient.class.php';`
`require 'debug.php';`
`$client = new RtmpClient();`
`$client->connect("rtmp-api.facebook.com","rtmp/10154781408839060?ds=1&s_l=1&a=AaZ4EJLdicjFaeq1", 80);`

**Comment by skrosoft** [comment]
Ok, i had to connect with the folowing:

`$client->connect("rtmp-api.facebook.com","rtmp/", 80);`

But do you know how to pass the "stream key" (10154781408839060?ds=1&s_l=1&a=AaZ4EJLdicjFaeq1) and how to say "closeStream"?

Thank you

**Comment by qwantix** [comment]
Hi, 
Sorry... I stopped the development of this project ( and PHP... ) a long ago.... And to be honest, I'm no longer able to tell you how it works... :/
Unfortunately I do not have time to get back into this project.. .
You can try fork of @furyfire ( https://github.com/furyfire/php-rtmp-client ), it seems he took over the project... :) 

Good luck!
